name: 00 -Main CI/CD Pipeline

on:
  push:
    paths-ignore:
      - "**/*.md"
      # ignore all markdown files
  workflow_dispatch: # Manual trigger for the workflow

jobs:
  lint-and-test:
    name: Linting
    uses: ./.github/workflows/quality.yml

  sca:
    uses: ./.github/workflows/sca.yml

  sast:
    uses: ./.github/workflows/sast.yml
